"""remove outstation from event membership

Revision ID: 035d4ee19930
Revises: 01aee445e2be
Create Date: 2026-09-25 23:26:16.817506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '035d4ee19930'
down_revision = '01aee445e2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_memberships', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_event_memberships_outstation_id'), type_='foreignkey')
        batch_op.drop_column('outstation_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outstation_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_event_memberships_outstation_id'), 'event_outstations', ['outstation_id'], ['id'])

    # ### end Alembic commands ###
