"""add event groups and moderator voting

Revision ID: 0e444b33549b
Revises: 426663143e86
Create Date: 2026-09-25 16:34:46.969830

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0e444b33549b"
down_revision = "426663143e86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event_groups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "name", name="uq_event_group_name"),
    )
    op.create_table(
        "event_outstations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "name", name="uq_event_outstation_name"),
    )
    op.create_table(
        "moderator_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("membership_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["event_memberships.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_id", "membership_id", name="uq_event_moderator_candidate"
        ),
    )
    op.create_table(
        "moderator_votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("voter_membership_id", sa.Integer(), nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["moderator_candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voter_membership_id"],
            ["event_memberships.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "event_id", "voter_membership_id", name="uq_event_moderator_voter"
        ),
    )
    with op.batch_alter_table("event_memberships", schema=None) as batch_op:
        batch_op.add_column(sa.Column("outstation_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("group_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_event_memberships_outstation_id",
            "event_outstations",
            ["outstation_id"],
            ["id"],
        )

        batch_op.create_foreign_key(
            "fk_event_memberships_group_id",
            "event_groups",
            ["group_id"],
            ["id"],
        )

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "moderator_voting_status",
                sa.String(length=50),
                nullable=False,
                server_default="NOT_STARTED",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("moderator_voting_status")

    with op.batch_alter_table("event_memberships", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_event_memberships_group_id",
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            "fk_event_memberships_outstation_id",
            type_="foreignkey",
        )
        batch_op.drop_column("group_id")
        batch_op.drop_column("outstation_id")

    op.drop_table("moderator_votes")
    op.drop_table("moderator_candidates")
    op.drop_table("event_outstations")
    op.drop_table("event_groups")
    # ### end Alembic commands ###
