"""expand event details and lifecycle

Revision ID: 426663143e86
Revises: 8dc87c890151
Create Date: 2026-09-24 20:25:46.090466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426663143e86'
down_revision = '8dc87c890151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venue', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('access_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('registration_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('voting_status', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_events_access_code'), ['access_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_access_code'))
        batch_op.drop_column('voting_status')
        batch_op.drop_column('registration_status')
        batch_op.drop_column('access_code')
        batch_op.drop_column('ends_at')
        batch_op.drop_column('starts_at')
        batch_op.drop_column('country')
        batch_op.drop_column('city')
        batch_op.drop_column('address')
        batch_op.drop_column('venue')

    # ### end Alembic commands ###
