"""add platform outstations

Revision ID: 4e514043852f
Revises: 0e444b33549b
Create Date: 2026-09-25 22:32:22.990313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e514043852f'
down_revision = '0e444b33549b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outstations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('outstations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outstations_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outstations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outstations_slug'))

    op.drop_table('outstations')
    # ### end Alembic commands ###
