"""add team roles to event memberships

Revision ID: 932f95768df5
Revises: cc887ac410ef
Create Date: 2026-09-26 00:55:46.762483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932f95768df5'
down_revision = 'cc887ac410ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_memberships', schema=None) as batch_op:
       batch_op.add_column(
           sa.Column(
               "team_role",
               sa.String(length=50),
               nullable=False,
               server_default="MEMBER",
           )
       )
    
# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_memberships', schema=None) as batch_op:
        batch_op.drop_column('team_role')

    # ### end Alembic commands ###
