"""add team leader votes

Revision ID: a07ec4ac1bb4
Revises: 932f95768df5
Create Date: 2026-09-26 01:03:16.546105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a07ec4ac1bb4'
down_revision = '932f95768df5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_leader_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('voter_membership_id', sa.Integer(), nullable=False),
    sa.Column('candidate_membership_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_membership_id'], ['event_memberships.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['event_groups.id'], ),
    sa.ForeignKeyConstraint(['voter_membership_id'], ['event_memberships.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'voter_membership_id', name='uq_team_leader_vote_voter')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_leader_votes')
    # ### end Alembic commands ###
