"""add custom team display names

Revision ID: cc887ac410ef
Revises: 035d4ee19930
Create Date: 2026-09-26 00:52:01.495764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc887ac410ef'
down_revision = '035d4ee19930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_groups', schema=None) as batch_op:
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
