"""add team leader election status

Revision ID: d00bc8627781
Revises: a07ec4ac1bb4
Create Date: 2026-09-26 01:19:57.655677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd00bc8627781'
down_revision = 'a07ec4ac1bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('election_status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_groups', schema=None) as batch_op:
        batch_op.drop_column('election_status')

    # ### end Alembic commands ###
